# Generated by Django 4.1.13 on 2024-11-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineactivity',
            name='field_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fieldactivity'),
        ),
        migrations.AddField(
            model_name='lineactivity',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.line'),
        ),
        migrations.AddField(
            model_name='lineactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='line',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.field'),
        ),
        migrations.AddField(
            model_name='fieldactivity',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.field'),
        ),
        migrations.AddField(
            model_name='field',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
