# Generated by Django 4.1.13 on 2024-11-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldactivity',
            name='activity_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
