# Generated by Django 4.1.13 on 2024-11-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fieldactivity_activity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldactivity',
            old_name='date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='field_activity',
        ),
        migrations.AddField(
            model_name='fieldactivity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
