# Generated by Django 4.1.13 on 2024-11-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_date_fieldactivity_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='address',
            new_name='name',
        ),
    ]
