# Generated by Django 4.1.13 on 2024-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_fieldactivity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineactivity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
