# Generated by Django 4.1.13 on 2024-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_lineactivity_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldactivity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
